#!/usr/bin/env python

Import("env")
Import("env_modules")

env_serial = env_modules.Clone()

# Thirdparty source files

serial_obj = []

serial_dir = "libserialport/"
serial_sources = ["serial_wrapper.c"]

if env["platform"] == "windows":
    if env.get("is_msvc", False):
        env.Append(LINKFLAGS=["setupapi.lib", "Advapi32.lib"])
    else:
        env.Append(LIBS=["setupapi", "advapi32"])
print("Build for {0}.".format(env["platform"]))

env_serial.Prepend(CPPPATH=[serial_dir])

#env_serial.disable_warnings()
env_serial.add_source_files(serial_obj, serial_sources)
env.modules_sources += serial_obj

# Godot source files

module_obj = []

env_serial.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the serial library is updated.
env.Depends(module_obj, serial_obj)

