#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPDEFINES=["GDEXTENSION"])
env.Append(CPPPATH=[".", "libserialport"])

addon_sources = [
    "register_types.cpp",
    "stream_peer_serial.cpp",
    "serial_port_config.cpp"
]

serial_dir = "libserialport/"
serial_sources = ["serial_wrapper.c"]

if env["platform"] == "windows":
    if env.get("is_msvc", False):
        env.Append(LINKFLAGS=["setupapi.lib", "Advapi32.lib"])
    else:
        env.Append(LIBS=["setupapi", "advapi32"])
print("Build for {0}.".format(env["platform"]))

addon_sources.append(serial_sources)
addon_name = "StreamPeerSerial"
addon_path = "gdextension_build/example/addons/{}".format(addon_name)
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{0}/bin/lib{1}.{2}.{3}.dylib".format(
            addon_path,
            addon_name,
            env["platform"],
            env["target"]
        ),
        source=addon_sources,
    )
elif env["platform"] == "windows":
    library = env.SharedLibrary(
        "{0}/bin/{1}{2}{3}".format(
            addon_path,
            addon_name,
            env["suffix"],
            env["SHLIBSUFFIX"]
        ),
        source=addon_sources,
    )
else:
    library = env.SharedLibrary(
        "{0}/bin/lib{1}{2}{3}".format(
            addon_path,
            addon_name,
            env["suffix"],
            env["SHLIBSUFFIX"]
        ),
        source=addon_sources,
    )

Default(library)
